project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands_on_Ex/Hands_on_Ex01/Hands_on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands_on_Ex/Hands_on_Ex03/Hands_on_Ex03.html"
          - text: "Hands-on Exercise 4a"
            href: "Hands_on_Ex/Hands_on_Ex04/Hands_on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands_on_Ex/Hands_on_Ex04/Hands_on_Ex04b.html"
          - text: "Hands-on Exercise 4c"
            href: "Hands_on_Ex/Hands_on_Ex04/Hands_on_Ex04c.html"
          - text: "Hands-on Exercise 5a"
            href: "Hands_on_Ex/Hands_on_Ex05/Hands_on_Ex05a.html"
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 3"
            href: "In_Class_Ex/In_Class_Ex03/In_Class_Ex03.html"
          - text: "In-Class Exercise 4"
            href: "In_Class_Ex/In_Class_Ex04/In_Class_Ex04.html"
          - text: "In-Class Exercise 5"
            href: "In_Class_Ex/In_Class_Ex05/In_Class_Ex05.html"
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-Home Exercise 1"
            href: "Take_Home_Ex/Take_Home_Ex01/Take_Home_Ex01.html"
          - text: "Take-Home Exercise 2"
            href: "Take_Home_Ex/Take_Home_Ex02/Take_Home_Ex02.html"
          - text: "Take-Home Exercise 3"
            href: "Take_Home_Ex/Take_Home_Ex03/Take_Home_Ex03.html"
    right: 
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-location: left
    page-layout: full

editor: visual

