---
title: "In-Class Exercise 3"
author: "Bhairavi"
date: 28 January 2023
date-modified: "`r Sys.Date()`"
execute:
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

Installing and loading R packages

Two packages will be installed and loaded. They are: tidyverse and ggiraph,

```{r}
pacman::p_load(ggiraph, tidyverse)
```

Importing data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```
Without interactivity:

```{r}
ggplot(data = exam_data,
       aes(x = MATHS)) +
  geom_dotplot(dotsize = 0.5)
```

With interactivity:

```{r}
tooltip_css <- "background-color:white; font-style:bold; color:black;"

p <- ggplot(data = exam_data,
            aes(x = MATHS)) +
  geom_dotplot_interactive(aes(tooltip = ID),
                           stackgroups = TRUE,
                           binwidth = 1,
                           method =  "histodot") +
  scale_y_continuous(NULL,
                     breaks = NULL)

girafe(ggobj = p,
       width_svg = 6,
       height_svg = 6*0.618,
       options = list(opts_tooltip(css = tooltip_css)))
```